### ISSUE TITLE
Dependency error unclear

### ISSUE THREAD

**Issue by tneullas** [wanadev/obsidianjs#68]
When you encounter an unmet depencency logged error should display name of the unmet depency, Instead it display "true".

It gives you :  
An error occured when starting the application: Error: UnmetDependency: "myModule" requires "true" but it cannot be found.

Expected :  
An error occured when starting the application: Error: UnmetDependency: "myModule" requires "myMissedDependency" but it cannot be found.

Error come from modules-loader file L163

**Comment by flozz** [comment]
Already fixed. Please double check you are using obsidianjs v0.3.x :)
